# Generated by Django 5.1.1 on 2025-04-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adoption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adoption',
        ),
    ]
