# Generated by Django 5.1.7 on 2025-03-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_volunteer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
