# Generated by Django 5.1.7 on 2025-03-09 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
