# Generated by Django 5.1.1 on 2025-04-11 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshops', '0003_order_items_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='petshops.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='petshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='petshops.petshop'),
        ),
    ]
