# Generated by Django 5.1.1 on 2025-04-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuerequest',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='rescuerequest',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
