# Generated by Django 5.1.1 on 2025-04-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_rescuerequest_contact_number_rescuerequest_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuerequest',
            name='predicted_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
