# Generated by Django 5.1.1 on 2025-04-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_rescuerequest_predicted_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rescuerequest',
            old_name='predicted_name',
            new_name='predicted_animal',
        ),
    ]
