# Generated by Django 5.1.7 on 2025-03-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_alter_volunteer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
