# Generated by Django 5.1.1 on 2025-04-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_rename_predicted_name_rescuerequest_predicted_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='volunteer_pictures/'),
        ),
    ]
