# Generated by Django 5.1.1 on 2025-03-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_rescuerequest_accepted_by_rescuerequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected', models.BooleanField(default=False)),
                ('rescue_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.rescuerequest')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteer')),
            ],
            options={
                'unique_together': {('volunteer', 'rescue_request')},
            },
        ),
    ]
