# Generated by Django 5.1.7 on 2025-03-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddPets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_images/')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('bread', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('health_vaccinations', models.CharField(max_length=100)),
            ],
        ),
    ]
