# Generated by Django 5.1.1 on 2025-04-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_addpets_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpets',
            old_name='user',
            new_name='owner',
        ),
    ]
