# Generated by Django 5.1.7 on 2025-03-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_adoptionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpets',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
    ]
