# Generated by Django 5.1.1 on 2025-03-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('petshop', 'Petshop'), ('volunteer', 'Volunteer')], default='normal', max_length=20),
        ),
    ]
